---
title: "Decision Tree Classifier"
output:
  md_document:
    variant: gfm
---

# Decision Tree

```{r}
# Load libraries
library(rpart)
library(caret)
library(knitr)

# Load helpers
source("./../helpers/helper.R")
```

## Import Data

```{r}
# Read training and testing data
train <- read.csv("./../data/classification_data/intermediates/train.csv")
test <- read.csv("./../data/classification_data/intermediates/test.csv")

# Drop index columns
drops <- c("X.1", "X")
train <- train[, !(names(train) %in% drops)]
test <- test[, !(names(test) %in% drops)]
```

## Model Training

```{r}
dtree.model <- rpart(Rating~., data=train, method = 'class')
```

## Model Validation

```{r}
# Predict the output for samples in test data using the model
result <- predict(dtree.model, test, type="class")

# Print the Confusion matrix
confusion.matrix <- confusionMatrix(as.factor(result), as.factor(test$Rating))
plot.custom.confusion.matrix(confusion.matrix$table)
```

```{r}
# Print the accuracy stats of the model
kable(data.frame(confusion.matrix$overall))
```

```{r}
# Print validation stats of the model
kable(data.frame(confusion.matrix$byClass))
```

```{r}
# Get the feature importance
kable(varImp(dtree.model))
```

```{r}
# Save the results
algorithm <- "Decision.Tree"
save.class.acc.result(confusion.matrix$overall, algorithm)
save.class.pvv.result(confusion.matrix$byClass, algorithm)
```

## Prediction with Unknown Data

```{r}
# Load the data
unk <- read.csv("./../data/classification_data/intermediates/unknown_data.csv")
dim(unk)

# Predict using the built model
prediction <- predict(dtree.model, unk)
final.pred = colnames(result)[apply(prediction,1,which.max)]
final.pred
```
