---
title: "kNN Classifier"
output:
  md_document:
    variant: gfm
---

# kNN

```{r}
# Load libraries
library(e1071)
library(caret)
library(knitr)

# Load helpers
source("./../helpers/helper.R")
```

## Import Data

```{r}
# Read training and testing data
train <- read.csv("./../data/classification_data/intermediates/train.csv")
test <- read.csv("./../data/classification_data/intermediates/test.csv")
```

## Model Training

```{r}
k.acc <- list()
ks <- c(3, 5, 9, 15, 23)
initial_accuracy <- 0
for (k in ks){
  print(k)
  knn.model <- knn3(as.factor(Rating)~., data=train, k=k)
  result <- predict(knn.model, test, type="class")
  sum(is.na(result))
  sum(is.na(test$Rating))
  accuracy <- mean(as.factor(result)==as.factor(test$Rating))
  k.acc <- append(k.acc, accuracy)
  print(accuracy)
  if (initial_accuracy < accuracy){
    initial_accuracy <- accuracy
    chosen_k <- k
  }
  print("\n")
}
print(chosen_k)
```

```{r}
k.acc <- unlist(k.acc)
plot(ks, k.acc, type="o", col="red", main="Accuracy for different values of K", xlab="Value of k", ylab="Accuracy of kNN model")
```

```{r}
# Retrain the model with chosen value of k
knn.model <- knn3(as.factor(Rating)~., data=train, k=chosen_k)
knn.model
```

## Model Validation

```{r}
# Use the new model for prediction
result <- predict(knn.model, test, type="class")

# Print the Confusion matrix
confusion.matrix <- confusionMatrix(as.factor(result), as.factor(test$Rating))
plot.custom.confusion.matrix(confusion.matrix$table)
```

```{r}
# Print the accuracy stats of the model
kable(data.frame(confusion.matrix$overall))
```

```{r}
# Print validation stats of the model
kable(data.frame(confusion.matrix$byClass))
```

```{r}
# Save the results
algorithm <- "kNN"
save.class.acc.result(confusion.matrix$overall, algorithm)
save.class.pvv.result(confusion.matrix$byClass, algorithm)
```
