---
title: "Random Forest Classifier"
output:
  md_document:
    variant: gfm
---

# Random Forest

```{r}
# Load libraries
library(randomForest)
library(caret)
library(knitr)

# Load helpers
source("./../helpers/helper.R")
```

## Import Data

```{r}
# Read training and testing data
train <- read.csv("./../data/classification_data/intermediates/train.csv")
test <- read.csv("./../data/classification_data/intermediates/test.csv")

# Drop index columns
drops <- c("X.1", "X")
train <- train[, !(names(train) %in% drops)]
test <- test[, !(names(test) %in% drops)]
```

## Model Training

```{r}
# Model Training
rf.model <- randomForest(as.factor(Rating)~., data=train)
rf.model
```

## Model Validation

```{r}
# Predict the samples from test data using the model
result <- predict(rf.model, test, type="class")

# Print the Confusion matrix
confusion.matrix <- confusionMatrix(as.factor(result), as.factor(test$Rating))
plot.custom.confusion.matrix(confusion.matrix$table)
```

```{r}
# Print the accuracy stats of the model
kable(data.frame(confusion.matrix$overall))
```

```{r}
# Print validation stats of the model
kable(data.frame(confusion.matrix$byClass))
```

```{r}
# Get the feature importances for each feature
kable(varImp(rf.model))
```

```{r}
# Plot feature importance
varImp.df <- data.frame(varImp(rf.model))
varImp.df$Overall <- varImp.df[order(varImp.df$Overall, decreasing = FALSE),]
par(mar=c(15,3,3,0))
barplot(varImp.df$Overall, names.arg=rownames(varImp.df), las=2, col="blue", main="Random Forest: Feature Importances")
```

```{r}
# Save the results
algorithm <- "Random.Forest"
save.class.acc.result(confusion.matrix$overall, algorithm)
save.class.pvv.result(confusion.matrix$byClass, algorithm)
```

## Prediction with Unknown Data

```{r}
# Load the data
unk <- read.csv("./../data/classification_data/intermediates/unknown_data.csv")
dim(unk)

# Predict using the built model
prediction <- predict(rf.model, unk)
prediction
```
