---
title: "Gradient Boosting Classifier"
output:
  md_document:
    variant: gfm
---

# Gradient Boosting

```{r}
# Load libraries
library(gbm)
library(caret)
library(knitr)

# Load helpers
source("./../helpers/helper.R")
```

## Import Data

```{r}
# Read training and testing data
train <- read.csv("./../data/classification_data/intermediates/train.csv")
test <- read.csv("./../data/classification_data/intermediates/test.csv")

# Drop index columns
drops <- c("X.1", "X")
train <- train[, !(names(train) %in% drops)]
test <- test[, !(names(test) %in% drops)]
```

## Model Training

```{r}
# Train the model
gbm.model = gbm(as.factor(Rating)~., data=train, distribution = "multinomial")
gbm.model
```

```{r}
# Predict the samples from test data using the model
result <- predict(gbm.model, test)

# Find the classes from the prediction probabilities
final.result = colnames(result)[apply(result,1,which.max)]

# Print the Confusion matrix
confusion.matrix <- confusionMatrix(as.factor(final.result), as.factor(test$Rating))
plot.custom.confusion.matrix(confusion.matrix$table)
```

```{r}
# Print the accuracy stats of the model
kable(data.frame(confusion.matrix$overall))
```

```{r}
# Print validation stats of the model
kable(data.frame(confusion.matrix$byClass))
```

```{r}
# Save the results
algorithm <- "Gradient.Boosting"
save.class.acc.result(confusion.matrix$overall, algorithm)
save.class.pvv.result(confusion.matrix$byClass, algorithm)
```

## Prediction with Unknown Data

```{r}
# Load the data
unk <- read.csv("./../data/classification_data/intermediates/unknown_data.csv")
dim(unk)

# Predict using the built model
prediction <- predict(gbm.model, unk)
final.pred = colnames(result)[apply(prediction,1,which.max)]
final.pred
```
