---
title: "Naive Bayes"
output:
  md_document:
    variant: gfm
---

# Naive Bayes

```{r}
# Load libraries
library(e1071)
library(caret)
library(knitr)

# Load helpers
source("./../helpers/helper.R")
```

## Import Data

```{r}
# Read training and testing data
train <- read.csv("./../data/classification_data/intermediates/train.csv")
test <- read.csv("./../data/classification_data/intermediates/test.csv")
```

## Model Training

```{r}
# Model training
nb.model <- naiveBayes(Rating~., data=train)
nb.model
```

## Model Validation

```{r}
# Predict the samples from test data using the model
result <- predict(nb.model, test)

# Print the Confusion matrix
confusion.matrix <- confusionMatrix(as.factor(result), as.factor(test$Rating))
plot.custom.confusion.matrix(confusion.matrix$table)
```

```{r}
# Print the accuracy stats of the model
kable(data.frame(confusion.matrix$overall))
```

```{r}
# Print validation stats of the model
kable(data.frame(confusion.matrix$byClass))
```

```{r}
# Save the results
algorithm <- "Naive.Bayes"
save.class.acc.result(confusion.matrix$overall, algorithm)
save.class.pvv.result(confusion.matrix$byClass, algorithm)
```
